// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Customer struct {
	ID       string  `json:"id"`
	Address  *string `json:"address"`
	Created  *int    `json:"created"`
	Currency *string `json:"currency"`
	Email    *string `json:"email"`
	Livemode *bool   `json:"livemode"`
	Name     *string `json:"name"`
	Phone    *string `json:"phone"`
}

type Invoice struct {
	ID               *string `json:"id"`
	Created          *int    `json:"created"`
	Currency         *string `json:"currency"`
	Customer         *string `json:"customer"`
	HostedInvoiceURL *string `json:"hosted_invoice_url"`
	Livemode         *bool   `json:"livemode"`
	Paid             *bool   `json:"paid"`
	PeriodEnd        *int    `json:"period_end"`
	PeriodStart      *int    `json:"period_start"`
	Status           *string `json:"status"`
	Subtotal         *int    `json:"subtotal"`
	Tax              *string `json:"tax"`
	Total            *int    `json:"total"`
}
